OPCODE_FLAG = ['', '+']
SYMBOL_FLAG = ['', '#', '@', '$']

OPCODE = {
    'ADD': {'mnemonic': 'ADD', 'format': 3, 'opcode': 0x18},
    'ADDF': {'mnemonic': 'ADDF', 'format': 3, 'opcode': 0x58},
    'ADDR': {'mnemonic': 'ADDR', 'format': 2, 'opcode': 0x90},
    'AND': {'mnemonic': 'AND', 'format': 3, 'opcode': 0x40},
    'CLEAR': {'mnemonic': 'CLEAR', 'format': 2, 'opcode': 0xb4},
    'COMP': {'mnemonic': 'COMP', 'format': 3, 'opcode': 0x28},
    'COMPF': {'mnemonic': 'COMPF', 'format': 3, 'opcode': 0x88},
    'COMPR': {'mnemonic': 'COMPR', 'format': 2, 'opcode': 0xa0},
    'DIV': {'mnemonic': 'DIV', 'format': 3, 'opcode': 0x24},
    'DIVF': {'mnemonic': 'DIVF', 'format': 3, 'opcode': 0x64},
    'DIVR': {'mnemonic': 'DIVR', 'format': 2, 'opcode': 0x9c},
    'FIX': {'mnemonic': 'FIX', 'format': 1, 'opcode': 0xc4},
    'FLOAT': {'mnemonic': 'FLOAT', 'format': 1, 'opcode': 0xc0},
    'HALT': {'mnemonic': 'HALT', 'format': 1, 'opcode': 0xe4},
    'HIO': {'mnemonic': 'HIO', 'format': 1, 'opcode': 0xf4},
    'J': {'mnemonic': 'J', 'format': 3, 'opcode': 0x3c},
    'JEQ': {'mnemonic': 'JEQ', 'format': 3, 'opcode': 0x30},
    'JGT': {'mnemonic': 'JGT', 'format': 3, 'opcode': 0x34},
    'JLT': {'mnemonic': 'JLT', 'format': 3, 'opcode': 0x38},
    'JNE': {'mnemonic': 'JNE', 'format': 3, 'opcode': 0x8c},
    'JSUB': {'mnemonic': 'JSUB', 'format': 3, 'opcode': 0x48},
    'LDA': {'mnemonic': 'LDA', 'format': 3, 'opcode': 0x00},
    'LDB': {'mnemonic': 'LDB', 'format': 3, 'opcode': 0x68},
    'LDCH': {'mnemonic': 'LDCH', 'format': 3, 'opcode': 0x50},
    'LDF': {'mnemonic': 'LDF', 'format': 3, 'opcode': 0x70},
    'LDL': {'mnemonic': 'LDL', 'format': 3, 'opcode': 0x08},
    'LDS': {'mnemonic': 'LDS', 'format': 3, 'opcode': 0x6c},
    'LDT': {'mnemonic': 'LDT', 'format': 3, 'opcode': 0x74},
    'LDX': {'mnemonic': 'LDX', 'format': 3, 'opcode': 0x04},
    'LPS': {'mnemonic': 'LDS', 'format': 3, 'opcode': 0xd0},
    'MUL': {'mnemonic': 'MUL', 'format': 3, 'opcode': 0x20},
    'MULF': {'mnemonic': 'MULF', 'format': 3, 'opcode': 0x60},
    'MULR': {'mnemonic': 'MULR', 'format': 2, 'opcode': 0x98},
    'NORM': {'mnemonic': 'NORM', 'format': 1, 'opcode': 0xc8},
    'OR': {'mnemonic': 'OR', 'format': 3, 'opcode': 0x44},
    'RD': {'mnemonic': 'RD', 'format': 3, 'opcode': 0xd8},
    'RMO': {'mnemonic': 'RMO', 'format': 2, 'opcode': 0xac},
    'RSUB': {'mnemonic': 'RSUB', 'format': 3, 'opcode': 0x4c},
    'SHIFTL': {'mnemonic': 'SHIFTL', 'format': 2, 'opcode': 0xa4},
    'SHIFTR': {'mnemonic': 'SHIFTR', 'format': 2, 'opcode': 0xa8},
    'SIO': {'mnemonic': 'SIO', 'format': 1, 'opcode': 0xf0},
    'SSK': {'mnemonic': 'SSK', 'format': 3, 'opcode': 0xec},
    'STA': {'mnemonic': 'STA', 'format': 3, 'opcode': 0x0c},
    'STB': {'mnemonic': 'STB', 'format': 3, 'opcode': 0x78},
    'STCH': {'mnemonic': 'STCH', 'format': 3, 'opcode': 0x54},
    'STF': {'mnemonic': 'STF', 'format': 3, 'opcode': 0x80},
    'STI': {'mnemonic': 'STI', 'format': 3, 'opcode': 0xd4},
    'STL': {'mnemonic': 'STL', 'format': 3, 'opcode': 0x14},
    'STS': {'mnemonic': 'STS', 'format': 3, 'opcode': 0x7c},
    'STSW': {'mnemonic': 'STSW', 'format': 3, 'opcode': 0xe8},
    'STT': {'mnemonic': 'STT', 'format': 3, 'opcode': 0x84},
    'STX': {'mnemonic': 'STX', 'format': 3, 'opcode': 0x10},
    'SUB': {'mnemonic': 'SUB', 'format': 3, 'opcode': 0x1c},
    'SUBF': {'mnemonic': 'SUBF', 'format': 3, 'opcode': 0x5c},
    'SUBR': {'mnemonic': 'SUBR', 'format': 2, 'opcode': 0x94},
    'SVC': {'mnemonic': 'SVC', 'format': 2, 'opcode': 0xb0},
    'TD': {'mnemonic': 'TD', 'format': 3, 'opcode': 0xe0},
    'TIO': {'mnemonic': 'TIO', 'format': 3, 'opcode': 0xf8},
    'TIX': {'mnemonic': 'TIX', 'format': 3, 'opcode': 0x2c},
    'TIXR': {'mnemonic': 'TIXR', 'format': 2, 'opcode': 0xb8},
    'WD': {'mnemonic': 'WD', 'format': 3, 'opcode': 0xdc},
}
DIRECTIVE = {
    'START': {'format': 2},
    'END': {'format': 2},
    'BYTE': {'format': 2},
    'WORD': {'format': 2},
    'RESB': {'format': 2},
    'RESW': {'format': 2},
    'FLOA': {'format': 2},
    'RESF': {'format': 2},
    'USE': {'format': 2},
    'ORG': {'format': 2},
    'LTORG': {'format': 2},
    'EXTDEF': {'format': 2},
    'EXTREF': {'format': 2},
    'EQU': {'format': 2},
    'BASE': {'format': 2},
    'CSECT': {'format': 2},
    'MACRO': {'format': 2},
    'MEND': {'format': 2},
}

MACRO = []
