SICXE_SIZE_BIT_BYTE = 8
SICXE_SIZE_BIT_HALFBYTE = int(SICXE_SIZE_BIT_BYTE / 2)
SICXE_SIZE_BIT_WORD = 24
SICXE_SIZE_BIT_FLOAT = 48
SICXE_OFFSETTER_FLOAT_EXPONENT = 1024
SICXE_SIZE_BIT_FLOAT_EXPONENT = 11
SICXE_SIZE_BIT_FLOAT_MANTISSA = 36
SICXE_SIZE_BYTE_WORD = int(SICXE_SIZE_BIT_WORD / SICXE_SIZE_BIT_BYTE)
SICXE_SIZE_BYTE_BYTE = int(SICXE_SIZE_BIT_BYTE / SICXE_SIZE_BIT_BYTE)
SICXE_SIZE_BYTE_FLOAT = int(SICXE_SIZE_BIT_FLOAT / SICXE_SIZE_BIT_BYTE)
SICXE_SIZE_MEMORY = 1 << 20
SICXE_SIZE_DEVICES = 0xff
SICXE_SIZE_BIT_EXPONENT = 11
SICXE_SIZE_BIT_MANTISSA = 36
SICXE_CC_GT = 0b10
SICXE_CC_LT = 0b01
SICXE_CC_EQ = 0b00

CC_MAP = {
    SICXE_CC_GT: '>',
    SICXE_CC_LT: '<',
    SICXE_CC_EQ: '==',
    0b11: ' '
}
