from debug.command.breakcommand import *
from debug.command.castcommand import *
from debug.command.command import *
from debug.command.disascommand import *
from debug.command.nextcommand import *
from debug.command.numbercommand import *
from debug.command.printcommand import *
from debug.command.registercommand import *
from debug.command.setcommand import *
from debug.command.token import *
from debug.command.exprcommand import *